import TopCards from '@/components/Card/TopCards';
import BarChart from '@/components/Chart/BarChart';
import RecentOrders from '@/components/Order/RecentOrders';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Admin Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-gray100 min-h-screen'>
        <TopCards />
        <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-4'>
          <BarChart />
          <RecentOrders />
        </div>
      </main>
    </>
  );
}
